version: "3"

services:
  master-node:
    build: ./blockchain
    environment:
      RPC_PORT: 8000
      RPC_PASSWORD: s750SiJnj50yIrmwxPnEdSzpfGlTAHzhaUwgqKeb0G1j
      ORGANIZATION: KfW 
      NODE_ENV: development
    ports:
      - "8000:8000" # port for connecting API
      - "8085:8085" # port for backup
      - "7447:7447" # port for connecting slaves (P2P)


