version: "3"
services:
  blockchain:
    build: .
    environment:
      RPC_PORT: ${RPC_PORT}
      RPC_PASSWORD: ${RPC_PASSWORD}
      ORGANIZATION: ${ORGANIZATION}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      MULTICHAIN_FEED: ${MULTICHAIN_FEED}
    ports:
      - "8000:8000"
      - "8085:8085"
